[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "scurrypy"
version = "2.3.2.0"

description = "Dataclass-driven Discord API Wrapper in Python"
readme = "README.md"
authors = [{ name = "Furmissile" }]
requires-python = ">=3.12"
dependencies = [
  "aiohttp>=3.8.0",
  "websockets>=11.0.0",
  "aiofiles>=23.0.0"
]

[tool.setuptools]
packages = [
  "scurrypy",
  "scurrypy.api",
  "scurrypy.api.channels",
  "scurrypy.api.commands",
  "scurrypy.api.components",
  "scurrypy.api.guilds",
  "scurrypy.api.interactions",
  "scurrypy.api.messages",
  "scurrypy.bases",
  "scurrypy.core",
  "scurrypy.enums",
  "scurrypy.events",
  "scurrypy.ext",
  "scurrypy.ext.cache",
  "scurrypy.ext.commands",
  "scurrypy.ext.components",
  "scurrypy.ext.events",
  "scurrypy.ext.interactions",
  "scurrypy.ext.prefixes",
  "scurrypy.params",
  "scurrypy.resources"
]

[tool.mypy]
python_version = "3.12"
pretty = true
strict = true
