from .enum_types import DiscordString

class EventType(DiscordString):
    """List of pre-defined event types.
    
    See Discord's [events](https://docs.discord.com/developers/events/gateway-events#receive-events) for more.
    """
    
    # startup events
    READY = 'READY'

    # audit log
    GUILD_AUDIT_LOG_ENTRY_CREATE = 'GUILD_AUDIT_LOG_ENTRY_CREATE'

    # automod events
    AUTO_MODERATION_RULE_CREATE = 'AUTO_MODERATION_RULE_CREATE'
    AUTO_MODERATION_RULE_UPDATE = 'AUTO_MODERATION_RULE_UPDATE'
    AUTO_MODERATION_RULE_DELETE = 'AUTO_MODERATION_RULE_DELETE'
    AUTO_MODERATION_ACTION_EXECUTION = 'AUTO_MODERATION_ACTION_EXECUTION'

    # channel events
    CHANNEL_CREATE = 'CHANNEL_CREATE'
    CHANNEL_UPDATE = 'CHANNEL_UPDATE'
    CHANNEL_DELETE = 'CHANNEL_DELETE'
    CHANNEL_PINS_UPDATE = 'CHANNEL_PINS_UPDATE'

    # guild events
    GUILD_CREATE = 'GUILD_CREATE'
    GUILD_UPDATE = 'GUILD_UPDATE'
    GUILD_DELETE = 'GUILD_DELETE'

    GUILD_BAN_ADD = 'GUILD_BAN_ADD'
    GUILD_BAN_REMOVE = 'GUILD_BAN_REMOVE'

    GUILD_EMOJIS_UPDATE = 'GUILD_EMOJIS_UPDATE'
    GUILD_STICKERS_UPDATE = 'GUILD_STICKERS_UPDATE'

    # guild members
    GUILD_MEMBER_ADD = 'GUILD_MEMBER_ADD'
    GUILD_MEMBER_UPDATE = 'GUILD_MEMBER_UPDATE'
    GUILD_MEMBER_REMOVE = 'GUILD_MEMBER_REMOVE'
    GUILD_MEMBERS_CHUNK = 'GUILD_MEMBERS_CHUNK'

    # guild scheduled events
    GUILD_SCHEDULED_EVENT_CREATE = 'GUILD_SCHEDULED_EVENT_CREATE'
    GUILD_SCHEDULED_EVENT_UPDATE = 'GUILD_SCHEDULED_EVENT_UPDATE'
    GUILD_SCHEDULED_EVENT_DELETE = 'GUILD_SCHEDULED_EVENT_DELETE'
    GUILD_SCHEDULED_EVENT_USER_ADD = 'GUILD_SCHEDULED_EVENT_USER_ADD'
    GUILD_SCHEDULED_EVENT_USER_REMOVE = 'GUILD_SCHEDULED_EVENT_USER_REMOVE'
    
    # integration events
    INTEGRATION_CREATE = 'INTEGRATION_CREATE'
    INTEGRATION_UPDATE = 'INTEGRATION_UPDATE'
    GUILD_INTEGRATIONS_UPDATE = 'GUILD_INTEGRATIONS_UPDATE'
    INTEGRATION_DELETE = 'INTEGRATION_DELETE'

    # interaction events
    INTERACTION_CREATE = 'INTERACTION_CREATE'

    # invite events
    INVITE_CREATE = 'INVITE_CREATE'
    INVITE_DELETE = 'INVITE_DELETE'

    # message events
    MESSAGE_CREATE = 'MESSAGE_CREATE'
    MESSAGE_UPDATE = 'MESSAGE_UPDATE'
    MESSAGE_DELETE = 'MESSAGE_DELETE'
    BULK_MESSAGE_DELETE = 'MESSAGE_DELETE_BULK'

    # poll events
    MESSAGE_POLL_VOTE_ADD = 'MESSAGE_POLL_VOTE_ADD'
    MESSAGE_POLL_VOTE_REMOVE = 'MESSAGE_POLL_VOTE_REMOVE'

    # reaction events
    MESSAGE_REACTION_ADD = 'MESSAGE_REACTION_ADD'
    MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE'
    MESSAGE_REACTION_REMOVE_EMOJI = 'MESSAGE_REACTION_REMOVE_EMOJI'
    MESSAGE_REACTION_REMOVE_ALL = 'MESSAGE_REACTION_REMOVE_ALL'
    
    # role events
    ROLE_CREATE = 'GUILD_ROLE_CREATE'
    ROLE_UPDATE = 'GUILD_ROLE_UPDATE'
    ROLE_DELETE = 'GUILD_ROLE_DELETE'

    # thread events
    THREAD_CREATE = 'THREAD_CREATE'
    THREAD_UPDATE = 'THREAD_UPDATE'
    THREAD_DELETE = 'THREAD_DELETE'
    THREAD_MEMBER_UPDATE = 'THREAD_MEMBER_UPDATE'
    THREAD_MEMBERS_UPDATE = 'THREAD_MEMBERS_UPDATE'
    THREAD_LIST_SYNC = 'THREAD_LIST_SYNC'

    # user events
    USER_UPDATE = 'USER_UPDATE'
    PRESENCE_UPDATE = 'PRESENCE_UPDATE'

    # webhook events
    WEBHOOKS_UPDATE = 'WEBHOOKS_UPDATE'

    # voice
    VOICE_CHANNEL_EFFECT_SEND = 'VOICE_CHANNEL_EFFECT_SEND'
    VOICE_STATE_UPDATE = 'VOICE_STATE_UPDATE'
    VOICE_SERVER_UPDATE = 'VOICE_SERVER_UPDATE'

    # stage instance
    STAGE_INSTANCE_CREATE = 'STAGE_INSTANCE_CREATE'
    STAGE_INSTANCE_UPDATE = 'STAGE_INSTANCE_UPDATE'
    STAGE_INSTANCE_DELETE = 'STAGE_INSTANCE_DELETE'

    # guild soundboard
    GUILD_SOUNDBOARD_SOUND_CREATE = 'GUILD_SOUNDBOARD_SOUND_CREATE'
    GUILD_SOUNDBOARD_SOUND_UPDATE = 'GUILD_SOUNDBOARD_SOUND_UPDATE'
    GUILD_SOUNDBOARD_SOUND_DELETE = 'GUILD_SOUNDBOARD_SOUND_DELETE'
    GUILD_SOUNDBOARD_SOUNDS_UPDATE = 'GUILD_SOUNDBOARD_SOUNDS_UPDATE'

    # entitlements
    ENTITLEMENT_CREATE = 'ENTITLEMENT_CREATE'
    ENTITLEMENT_UPDATE = 'ENTITLEMENT_UPDATE'
    ENTITLEMENT_DELETE = 'ENTITLEMENT_DELETE'
    
    # subscriptions
    SUBSCRIPTION_CREATE = 'SUBSCRIPTION_CREATE'
    SUBSCRIPTION_UPDATE = 'SUBSCRIPTION_UPDATE'
    SUBSCRIPTION_DELETE = 'SUBSCRIPTION_DELETE'
